### ISSUE TITLE
Practica #1

### ISSUE THREAD

**Issue by Band-hi** [SistemasTecTlaxiaco/practica-de-validacion-de-propuesta-de-valor-remi#2]
[Practica #1 - Validacion Elicitacion de Requisitos.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-validacion-de-propuesta-de-valor-remi/files/8126995/Practica.1.-.Validacion.Elicitacion.de.Requisitos.pdf)

**Comment by DuilioAquino10** [comment]
Calificación 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado
